#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade HG on Thu Mar 24 19:35:55 2011

import wx

from fsync import FileSync
from changesdialog import ActionsDialog

try:
    import cPickle as pickle
except:
    import pickle

# begin wxGlade: extracode
# end wxGlade



class FsyncDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FsyncDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.combo_box_1 = wx.ComboBox(self.panel_1, -1, choices=[], style=wx.CB_DROPDOWN)
        self.sizer_4_staticbox = wx.StaticBox(self.panel_1, -1, _("Source"))
        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, -1, "")
        self.sizer_5_staticbox = wx.StaticBox(self.panel_1, -1, _("Destination"))
        self.button_1 = wx.Button(self, wx.ID_OK, "")
        self.button_2 = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOK, self.button_1)
        # end wxGlade
        try:
            f = open("fsync.dat", "r")
            self.items = pickle.load(f)
            f.close()
        except:
            self.items = {}
            
        for k,v in self.items.items():
            self.combo_box_1.Append(k, v)
            
        self.Bind(wx.EVT_COMBOBOX, self.OnComboText)

    def __set_properties(self):
        # begin wxGlade: FsyncDialog.__set_properties
        self.SetTitle(_("fsync"))
        self.SetSize((400,160))
        self.panel_1.SetMinSize((400, 160))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FsyncDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_5_staticbox.Lower()
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        self.sizer_4_staticbox.Lower()
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        sizer_4.Add(self.combo_box_1, 1, wx.ALL|wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 0, wx.ALL|wx.EXPAND, 0)
        sizer_5.Add(self.text_ctrl_1, 1, wx.ALL, 0)
        sizer_3.Add(sizer_5, 0, wx.ALL|wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_3)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        sizer_2.Add(self.button_1, 0, 0, 0)
        sizer_2.Add(self.button_2, 0, wx.LEFT, 10)
        sizer_1.Add(sizer_2, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnComboText(self, event): # wxGlade: FsyncDialog.<event_handler>
        for k,v in self.items.items():
            if k == self.combo_box_1.GetValue():
                self.text_ctrl_1.SetValue(v)
                break

    def OnOK(self, event): # wxGlade: FsyncDialog.<event_handler>
        src = self.combo_box_1.GetValue()
        dst = self.text_ctrl_1.GetValue()
        fsync = FileSync(src, dst)
        fsync.compare()
        dlg = ActionsDialog(None, -1, "Changes", fsync.actions)
        dlg.ShowModal()
        fsync.actions = dlg.actions        
        dlg.Destroy()

        self.items[src] = dst
        f = open("fsync.dat", "w")
        f.write(pickle.dumps(self.items))
        f.close()
        def cb(*args):
            print " ".join(args)
        fsync.sync(callback=cb)
        fsync.close()
# end of class FsyncDialog


if __name__ == "__main__":
    import gettext
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    app.MainLoop()
    fsync_dialog = FsyncDialog(None, -1, "")
    app.SetTopWindow(fsync_dialog)
    fsync_dialog.ShowModal()
    fsync_dialog.Destroy()
